;HARSHIT SRIVASTAVA 19BCE0382
DATA SEGMENT
ADDADJUST DB ? ; ADD ANSWER
SUBADJUST DB ? ; SUB ANSWER
MULADJUST DB ? ; MUL ANSWER
DIVADJUST DB ? ; DIV ANSWER
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE, DS:DATA
START: MOV AX,DATA
MOV DS,AX           ; INITIALISE DS
MOV AL,09           ; 9 IN AL
MOV BL,08           ; 8 IN BL
ADD AL,BL           ; ADD
AAA                 ; AAA ADJUSTMENT
MOV ADDADJUST,AL  ; STORE ANSWER
MOV AL,9            ; 9 IN AL, 6IN BL   
MOV BL,6
SUB AL,BL           ; SUB
AAS                 ; AAS
MOV SUBADJUST,AL  ; STORE ANSWER
MOV AL,04           ; 4 IN AL
MOV BL,09           ; 9 IN BL
MUL BL              ; MUL
AAM                 ;AAM 
MOV MULADJUST,AL  ; STORE ANSWER
MOV AL,05           ; 5 IN AL
MOV BL,03            ; 3 IN BL
AAD                 ; AAD BEFORE DIV
DIV BL              ; DIVIDE OP
MOV DIVADJUST,AL  ; STORE ANSWER
MOV AH,4CH
INT 21H
CODE ENDS
END START