;HARSHIT SRIVASTAVA 19BCE0382
DATA SEGMENT
BIN DW 25H     ;BINARY INPUT
BCD DW ?       ;BCD OUTPUT
DATA ENDS 

CODE SEGMENT 
ASSUME CS:CODE, DS:DATA
START:
MOV AX, DATA        ;INTIALIZE DATA SEGMENT
MOV DS, AX
MOV BX, BIN     ;BX IS NOW HAVING BCD NUMBER
MOV CX, 0       ; INITIALIZATION   
MOV AX,0
REPEAT:                               
CMP BL, 0       ;COMPARISION TO CHECK BCD NUM IS ZERO       
JZ ENDPROG      ; IF ZERO END THE PROGRAM 
DEC BX
MOV AL, CL      ; 8 LSBs OF NUMBER IS TRANSFERRED TO AL
ADD AL, 1       ; SUBTRACT ONE FROM AL
DAA             ; DECIMAL DJUST AFTER SUBTRACTION
MOV CL, AL      ; RESULT IS STORED IN BL
MOV AL, CH      ; BMSB IS TRANSFERED TO AL
ADC AL, 00H     ; SUBTRACTION WITH BORROW
DAA             ; DECIMAL ADJUST AFTER SUBTRACTION
MOV CH, AL      ; RESULT BACK IN BH REGISTER
JMP REPEAT 
ENDPROG:
MOV BCD, CX ; RESULT IS DTORED IN DATA  
MOV AH, 4CH     ; TERMINATION OF PROGRAM
INT 21H         ; TERMINATION OF PROGRAM
CODE ENDS
END START