;HARSHIT SRIVASTAVA 19BCE0382
DATA SEGMENT
LIST DB 09H,18H,01H,0AH,03H ;LIST OF 5NUMBERS
COUNT EQU 05H               ; SIZE OF LIST EQUAL TO 5
LARGEST DB ?                ;STORE LARGEST
SMALLEST DB ?               ;STORE SMALLEST
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE, DS:DATA
START: MOV AX,DATA         ;MOV DATA TO AX
MOV DS,AX               ; INITIALISE DS
MOV SI, OFFSET LIST     ;OFFSET OF LIST IN SI
MOV CL,COUNT            ; STORE COUNT IN CL
MOV AL,[SI]             ;MOV FIRST ELEMENT OF LIST IN AL
LARGE: CMP AL,[SI+1]    ; COMPARE AL AND NEXT ELEMENT IN LIST
JNL NEXT                ;JUMP TO NEXT IF AL>[SI+1]
MOV AL,[SI+1]           ;INSTEAD OF JUMP STORE SI+1 IN AL
NEXT: INC SI            ; INC SI
DEC CL                  ; DECREASE COUNT
JNZ LARGE               ;JUMP TO LARGE IF NOT ZERO
MOV SI,OFFSET LARGEST   ;OFFSET OF LARGEST
MOV [SI],AL             ;STORE VALUE
XOR AX,AX               ;CLEAR AX
XOR CX,CX               ;CLEAR CX
MOV SI, OFFSET LIST     ;OFFSET OF LIST IN SI
MOV CL,COUNT            ; STORE COUNT IN CL
MOV AL,[SI]             ;MOV FIRST ELEMENT OF LIST IN AL
SMALL: CMP AL,[SI+1]    ; COMPARE AL AND NEXT ELEMENT IN LIST
JL NEXT2                ;JUMP TO NEXT2 IF AL<[SI+1]
MOV AL,[SI+1]           ;INSTEAD OF JUMP STORE SI+1 IN AL
NEXT2: INC SI           ; INC SI
DEC CL                  ; DECREASE COUNT
JNZ SMALL               ;JUMP TO SMALL IF NOT ZERO
MOV SI,OFFSET SMALLEST  ;OFFSET OF LARGEST
MOV [SI],AL             ;STORE VALUE
MOV AH,4CH              ;INTERRUPT OPTION
INT 21H                 ; INTERRUPT CALL
CODE ENDS
END START