;HARSHIT SRIVASTAVA
DATA SEGMENT
NUMBERS DB 00111111b, 00000110b, 01011011b
DATA ENDS ;DATA DISPLAYED ON OUR DISPLAY

CODE SEGMENT
ASSUME CS:CODE, DS:DATA, ES:DATA
START: PUSH DS ;PUSH DATA IN STACK
MOV AX,0
PUSH AX    ;PUSH AX
MOV AX,DATA;INITIALISE DATA
MOV DS,AX
MOV ES,AX  ;INITIALISE EXTRA
MOV DX,2030H ;FIRST 7 SEG DISPLAY
MOV SI,0     ;START FROM 0
MOV CX,8     ;COUNT TILL 8
NEXT:
MOV AL,NUMBERS[SI]
OUT DX,AL
INC SI
INC DX
LOOP NEXT
RET ;RETURN TO OS
CODE ENDS
END START